<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            [
                'name' => 'LD Admin',
                'role_id' => 1,
                'team_id' => null,
                'email' => 'admin@gmail.com',
                'password' => bcrypt('12345678'),
                'phone' => '03328547963',
                'gender' => 'MALE',
                'dob' => '1992-05-21',
                'address' => 'A-695 DHA phase-6',
                'is_active' => 1,
                'is_leader' => 0,
                'created_at' => \Carbon\Carbon::now(),
            ],
            [
                'name' => 'Marry kom',
                'role_id' => 2,
                'team_id' => 1,
                'email' => 'leader@gmail.com',
                'password' => bcrypt('12345678'),
                'phone' => '03328547962',
                'gender' => 'FEMALE',
                'dob' => '1988-05-21',
                'address' => 'A-691 DHA phase-2',
                'is_active' => 1,
                'is_leader' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            [
                'name' => 'jhon kim',
                'role_id' => 2,
                'team_id' => 2,
                'email' => 'leader1@gmail.com',
                'password' => bcrypt('12345678'),
                'phone' => '03328547962',
                'gender' => 'MALE',
                'dob' => '1987-05-21',
                'address' => 'A-991 DHA phase-6',
                'is_active' => 1,
                'is_leader' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            [
                'name' => 'david ops',
                'role_id' => 2,
                'team_id' => 3,
                'email' => 'leader2@gmail.com',
                'password' => bcrypt('12345678'),
                'phone' => '03328547962',
                'gender' => 'FEMALE',
                'dob' => '1989-05-21',
                'address' => 'A-791 DHA phase-3',
                'is_active' => 1,
                'is_leader' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            [
                'name' => 'Byron Mclaughlin',
                'role_id' => 2,
                'team_id' => 4,
                'email' => 'leader3@gmail.com',
                'password' => bcrypt('12345678'),
                'phone' => '03328547962',
                'gender' => 'MALE',
                'dob' => '1987-05-21',
                'address' => 'A-991 DHA phase-6',
                'is_active' => 1,
                'is_leader' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            [
                'name' => 'McKenzie Moses',
                'role_id' => 2,
                'team_id' => 5,
                'email' => 'leader4@gmail.com',
                'password' => bcrypt('12345678'),
                'phone' => '03328547962',
                'gender' => 'FEMALE',
                'dob' => '1989-05-21',
                'address' => 'A-791 DHA phase-3',
                'is_active' => 1,
                'is_leader' => 1,
                'created_at' => \Carbon\Carbon::now(),
            ],
            [
                'name' => 'Raven Salas',
                'role_id' => 3,
                'team_id' => 1,
                'email' => 'member@gmail.com',
                'password' => bcrypt('12345678'),
                'phone' => '03328547961',
                'gender' => 'MALE',
                'dob' => '1993-05-21',
                'address' => 'A-699 DHA phase-8',
                'is_active' => 1,
                'is_leader' => 0,
                'created_at' => \Carbon\Carbon::now(),
            ],
            [
                'name' => 'Ariana Stephenson',
                'role_id' => 3,
                'team_id' => 2,
                'email' => 'member1@gmail.com',
                'password' => bcrypt('12345678'),
                'phone' => '03328547961',
                'gender' => 'FEMALE',
                'dob' => '1993-05-21',
                'address' => 'A-699 DHA phase-8',
                'is_active' => 1,
                'is_leader' => 0,
                'created_at' => \Carbon\Carbon::now(),
            ],
            [
                'name' => 'Kylan Wilder',
                'role_id' => 3,
                'team_id' => 3,
                'email' => 'member2@gmail.com',
                'password' => bcrypt('12345678'),
                'phone' => '03328547961',
                'gender' => 'FEMALE',
                'dob' => '1993-05-21',
                'address' => 'A-699 DHA phase-8',
                'is_active' => 1,
                'is_leader' => 0,
                'created_at' => \Carbon\Carbon::now(),
            ],
            [
                'name' => 'Cailin Sampson',
                'role_id' => 3,
                'team_id' => 4,
                'email' => 'member3@gmail.com',
                'password' => bcrypt('12345678'),
                'phone' => '03328547961',
                'gender' => 'MALE',
                'dob' => '1993-05-21',
                'address' => 'A-699 DHA phase-8',
                'is_active' => 1,
                'is_leader' => 0,
                'created_at' => \Carbon\Carbon::now(),
            ],
            [
                'name' => 'Meredith Ray',
                'role_id' => 3,
                'team_id' => 5,
                'email' => 'member4@gmail.com',
                'password' => bcrypt('12345678'),
                'phone' => '03328547961',
                'gender' => 'MALE',
                'dob' => '1993-05-21',
                'address' => 'A-699 DHA phase-8',
                'is_active' => 1,
                'is_leader' => 0,
                'created_at' => \Carbon\Carbon::now(),
            ],
        ];

        DB::table('users')->insert($users);
    }
}
